### ISSUE TITLE
WordPress error indication

### ISSUE THREAD

**Issue by bakingem** [vexing-media/DigiTimber-cPanel-Integration-WP-Plugin#12]
After installation, WordPress indicates an error.

"The plugin generated 1 character of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin."

The error was fixed by copying the codes one by one and copying them (https://github.com/vexing-media/DigiTimber-cPanel-Integration-WP-Plugin)
and pasted it with the appropriate wordpress plugin editor.

---------------------------------------------------------------------------------------------------------------------------------------
In the future, what would be needed is what we would pay for.
In the cPanel whois directory, look for an available domain or an available email address that visitors can book through the website.

**Comment by digitimber** [comment]
Resolved in v1.4.6
